apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
  labels:
    app: my-flask-app
spec:
  selector:
    app: my-flask-app
  type: NodePort # Expose the service on a port on each node
  ports:
    - protocol: TCP
      port: 80 # Service port (internal to cluster)
      targetPort: 80 # Container port
      nodePort: 30080 # **Choose a port between 30000-32767. This is the port you'll use to access the app from Windows.**